services:
  - type: web
    name: petverse
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0